import type { RuleCatalog } from "../../core/types.js";

/**
 * 1040-simple TypeScript Catalog (v1)
 * Derived from 1040-simple.algos.agentx-v1.md
 */
export const SIMPLE_1040_CATALOG: RuleCatalog = {
  specialty: "1040-simple",
  version: 1,
  created_at: "2025-03-12T00:00:00.000Z",
  flow: [
    { id: "TX.ID.001", name: "SSN/TIN format", order: 1 },
    { id: "TX.ID.002", name: "Filing status required", order: 2 },
    { id: "TX.W2.010", name: "W-2 wages required", order: 3 },
    { id: "TX.W2.011", name: "W-2 box 1 = Line 1a", order: 4 },
    { id: "TX.MATH.020", name: "AGI flow", order: 5 },
    { id: "TX.MATH.021", name: "Taxable income", order: 6 },
    { id: "TX.MATH.022", name: "Tax from table", order: 7 },
    { id: "TX.SIGN.030", name: "Signature and date", order: 8 },
  ],
  rules: {
    "TX.ID.001": {
      id: "TX.ID.001",
      name: "SSN/TIN format",
      type: "interpreted",
      inputs: ["taxpayer"],
      output: "PASS_FAIL",
      handler: "evaluateIdentificationRule",
      description: "SSN is XXX-XX-XXXX or 9 digits",
      remediation: "Provide valid SSN",
      shortCircuit: false,
    },
    "TX.ID.002": {
      id: "TX.ID.002",
      name: "Filing status required",
      type: "interpreted",
      inputs: ["form1040"],
      output: "PASS_FAIL",
      handler: "evaluateIdentificationRule",
      description: "filing_status is Single",
      remediation: "Set filing_status to Single",
      shortCircuit: false,
    },
    "TX.W2.010": {
      id: "TX.W2.010",
      name: "W-2 wages required",
      type: "interpreted",
      inputs: ["w2s"],
      output: "PASS_FAIL",
      handler: "evaluateMathRule",
      description: "At least one W-2 with wages > 0",
      remediation: "Add W-2 with wages",
      shortCircuit: false,
    },
    "TX.W2.011": {
      id: "TX.W2.011",
      name: "W-2 box 1 = Line 1a",
      type: "interpreted",
      inputs: ["w2s", "form1040"],
      output: "PASS_FAIL",
      handler: "evaluateMathRule",
      description: "Sum W-2 box 1 equals Line 1a",
      remediation: "Reconcile W-2 total with Line 1a",
      shortCircuit: false,
    },
    "TX.MATH.020": {
      id: "TX.MATH.020",
      name: "AGI flow",
      type: "interpreted",
      inputs: ["form1040"],
      output: "PASS_FAIL",
      handler: "evaluateMathRule",
      description: "Line 11 = Line 9 for simple",
      remediation: "AGI = total income for simple return",
      shortCircuit: false,
    },
    "TX.MATH.021": {
      id: "TX.MATH.021",
      name: "Taxable income",
      type: "interpreted",
      inputs: ["form1040"],
      output: "PASS_FAIL",
      handler: "evaluateMathRule",
      description: "Line 15 = Line 11 - Line 14",
      remediation: "Recalculate taxable = AGI - standard deduction",
      shortCircuit: false,
    },
    "TX.MATH.022": {
      id: "TX.MATH.022",
      name: "Tax from table",
      type: "interpreted",
      inputs: ["form1040"],
      output: "PASS_FAIL",
      handler: "evaluateMathRule",
      description: "Line 16 matches Tax Table",
      remediation: "Use IRS Tax Table",
      shortCircuit: false,
    },
    "TX.SIGN.030": {
      id: "TX.SIGN.030",
      name: "Signature and date",
      type: "interpreted",
      inputs: ["form1040"],
      output: "PASS_FAIL",
      handler: "evaluateIdentificationRule",
      description: "Return signed and dated",
      remediation: "Sign and date the return",
      shortCircuit: false,
    },
  },
};
