export { default as Landing } from './Landing'
export { default as Dashboard } from './Dashboard'
export { default as Jobs } from './Jobs'
export { default as JobDetail } from './JobDetail'
export { default as JobConfig } from './JobConfig'
export { default as Candidates } from './Candidates'
export { default as CandidateAssessment } from './CandidateAssessment'
export { default as Analytics } from './Analytics'
export { default as JobChat } from './JobChat'
export { default as Settings } from './Settings'

