services:
  billy-relativity:
    image: jcrupi/billy-relativity:latest
    pull_policy: always
    container_name: billy-relativity
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PORT=8080
